build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/**/script/**/*.kts

dependencies:
  - buildSrc/**/*
  - gradlePlugin/test-util-dependency/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Library
mw-client:
  - mw-client/**/*

# Tests
mw-client-e2e:
  - mw-client-e2e/**/*
# Features

# AppAndroid
app:
  - app-android/**/*
